### ISSUE TITLE
incompatible with falsetweaks and codechickencore

### ISSUE THREAD

**Issue by Universal118** [LegacyModdingMC/UniMixins#1]
[fml-client-latest.log](https://github.com/LegacyModdingMC/UniMixins/files/10713802/fml-client-latest.log)

**Comment by makamys** [comment]
Try disabling `STARTUP_OPTIMIZATIONS` in FalseTweaks's config, I recall it causing issues with either GTNHMixins (which UniMixins embeds) or Hodgepodge (which you also have).

**Comment by MagmaBro123** [comment]
I'm using these features and UM doesn't seem to crap itself.
