### ISSUE TITLE
[Question] For what this needed?

### ISSUE THREAD

**Issue by iocmet** [LegacyModdingMC/UniMixins#10]

**Comment by makamys** [comment]
This mod is a library that's required by some mods ([ArchaicFix](https://github.com/embeddedt/ArchaicFix), [NotFine](https://github.com/jss2a98aj/NotFine), and [Hodgepodge](https://github.com/GTNewHorizons/Hodgepodge) are some examples.)

**Comment by makamys** [comment]
Oh. The main features are:
* The ability to safely use Mixin without having to embed it in your jar
* The ability to mix into the classes of mods that are not coremods using *late mixins*, which are mixins that get loaded after Forge has put all mods on the class path.
* MixinExtras adds some injectors, see its [wiki](https://github.com/LlamaLad7/MixinExtras/wiki)
