### ISSUE TITLE
why i just crash?

### ISSUE THREAD

**Issue by iamsoNewBee** [LegacyModdingMC/UniMixins#11]
[minecraft-exported-crash-info-2023-05-07T08-14-13.zip](https://github.com/LegacyModdingMC/UniMixins/files/11413614/minecraft-exported-crash-info-2023-05-07T08-14-13.zip)

**Comment by makamys** [comment]
Something is loading `FMLConstructionEvent` earlier than expected, but I can't tell what it is. Your launcher has a weird incomplete logger config which isn't helping.

You can try adding D-Tools (the latest build is [here](https://github.com/makamys/DTools/suites/11415616473/artifacts/588049436)) and enabling `logClassLoading` in the config. It will create a log in `.minecraft/dtools/out/class-load.log`, post it here.

**Comment by iamsoNewBee** [comment]
maybe it`s because it crashed so quickly that there is no time to generate that.however i will try

**Comment by makamys** [comment]
> Your launcher has a weird incomplete logger config which isn't helping.

About this, can you post your `G:\BaiduNetdiskDownload\Forge\bf\.minecraft\versions\1.7.10\log4j2.xml`? I want to check what's going on with it.

**Comment by iamsoNewBee** [comment]
[log4j2.zip](https://github.com/LegacyModdingMC/UniMixins/files/11414586/log4j2.zip)

**Comment by iamsoNewBee** [comment]
wait maybe it`s a nomal because i have remove that. let me try  again

**Comment by iamsoNewBee** [comment]
maybe have to do with falsetweaks.i just succeed one time miraculously and then crashed

**Comment by iamsoNewBee** [comment]
[log4j2.zip](https://github.com/LegacyModdingMC/UniMixins/files/11414709/log4j2.zip)
[minecraft-exported-crash-info-2023-05-07T18-18-06.zip](https://github.com/LegacyModdingMC/UniMixins/files/11414710/minecraft-exported-crash-info-2023-05-07T18-18-06.zip)
[class-load.log](https://github.com/LegacyModdingMC/UniMixins/files/11414711/class-load.log)(i started many times but there is only this one there.)

**Comment by makamys** [comment]
> [log4j2.zip](https://github.com/LegacyModdingMC/UniMixins/files/11414586/log4j2.zip)

Like I expected, it's pretty barebones. This is the config Forge is supposed to use: https://raw.githubusercontent.com/MinecraftForge/MinecraftForge/1.7.10/fml/src/main/resources/log4j2.xml

If you were able to set it as your log4j config, you'd get a more helpful log. One of these ways should work:
- Replace `G:\BaiduNetdiskDownload\Forge\bf\.minecraft\versions\1.7.10\log4j2.xml` with this file
- Download it elsewhere and set the `log4j.configurationFile` JVM property to its path (e.g. `-Dlog4j.configurationFile="G:\BaiduNetdiskDownload\the-other-log4j2.xml"`)

You know it works if you see `Preparing mixins for MixinEnvironment[PREINIT]` in `fml-client-latest.log`.

> maybe have to do with falsetweaks

Maybe it's caused by `STARTUP_OPTIMIZATIONS`.

**Comment by iamsoNewBee** [comment]
one detail:it crash within 1 seconds.i think it`s all whcih can generated.but i will have a try

**Comment by iamsoNewBee** [comment]
[log4j2.zip](https://github.com/LegacyModdingMC/UniMixins/files/11414764/log4j2.zip)

**Comment by makamys** [comment]
What's this? It's the same as before.

**Comment by iamsoNewBee** [comment]
i did as what u told me:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/98573273/236672317-def124c0-6841-4703-a021-bc62b7736d1a.png">
maybe i should send my mod file to let u reappear this issue by yourself..

**Comment by makamys** [comment]
> i did as what u told me

I guess it gets reset if you try to change it.

> maybe i should send my mod file to let u reappear this issue by yourself..

That would be nice.

**Comment by iamsoNewBee** [comment]
wait a moment*

**Comment by iamsoNewBee** [comment]
https://cowtransfer.com/s/28608d439f944a 点击链接查看 [ issue.zip ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 dvprdo 查看；

**Comment by iamsoNewBee** [comment]
by the wat the water in my world keep twitching about which i have no idea

**Comment by iamsoNewBee** [comment]
can u receive that?

**Comment by makamys** [comment]
> can u receive that?

Yeah, I did.

> by the way the water in my world keep twitching about which i have no idea

Sounds like this issue: https://github.com/embeddedt/ArchaicFix/issues/17. It was fixed recently (but no release has been made yet.)

**Comment by iamsoNewBee** [comment]
any clues？

**Comment by makamys** [comment]
I'm still curious about the log4j config issue. I've made a small mod that I believe fixes it by forcing Forge's default config to be used. Can you give it a try? You just have to put it in your mods folder and post a log again.

[+++NotEnoughVerbosity-1.7.10-0.1.zip](https://github.com/LegacyModdingMC/UniMixins/files/11415078/%2B%2B%2BNotEnoughVerbosity-1.7.10-0.1.zip)

**Comment by iamsoNewBee** [comment]
[minecraft-exported-crash-info-2023-05-07T21-39-48.zip](https://github.com/LegacyModdingMC/UniMixins/files/11415098/minecraft-exported-crash-info-2023-05-07T21-39-48.zip)
[class-load.log](https://github.com/LegacyModdingMC/UniMixins/files/11415100/class-load.log)
[log4j2.zip](https://github.com/LegacyModdingMC/UniMixins/files/11415104/log4j2.zip)
so cant u reappear it?

**Comment by makamys** [comment]
I tried running your pack and I do get the crash, I just wondered if I could solve the logging issue, since I see it a lot when people report issues. And it did work. Unfortunately, even the more detailed log doesn't say anything about what's loading `FMLConstructionEvent`. 😅 So it's a good thing you sent the pack.

**Comment by makamys** [comment]
Hold on, I looked at `class-load.log` again and there's something I missed

```
[DEFAULT] makamys.dmod.MixinConfigPlugin
[DEFAULT] makamys.dmod.ConfigDMod
[DEFAULT] makamys.dmod.ConfigDMod$ForceableBoolean
[DEFAULT] makamys.dmod.entity.EntityFox$AbilityMode
[DEFAULT] cpw.mods.fml.common.event.FMLConstructionEvent
```

It's caused by D-Mod. It's an old bug that got fixed later. Try again with [the latest version](https://github.com/makamys/DMod/releases/latest).

**Comment by iamsoNewBee** [comment]
:O

**Comment by iamsoNewBee** [comment]
hey，maybe the&nbsp;Occlusion Culling enabled in config of&nbsp;Archaic Fix caused the twitches ofwater in my pack

**Comment by makamys** [comment]
I'm not actually sure what exactly you mean by "twitching", it would be helpful if you posted a video.

(Also we should move to ArchaicFix's issue tracker.)

**Comment by iamsoNewBee** [comment]
wait for a moment.

**Comment by iamsoNewBee** [comment]
https://github.com/embeddedt/ArchaicFix/issues/91
