### ISSUE TITLE
Crash on startup with loading profiler caused by unimixin

### ISSUE THREAD

**Issue by quentin452** [LegacyModdingMC/UniMixins#17]
This is didn't appear without unimixins

crash : 

[crash-2023-10-07_13.06.15-client.txt](https://github.com/LegacyModdingMC/UniMixins/files/12837563/crash-2023-10-07_13.06.15-client.txt)

**Comment by makamys** [comment]
LoadingProfiler replaces every transformer in the transformer chain with wrapper objects of a single type. This is exactly as disastrous for compatibility as it sounds. There is nothing we can realistically do here, the mod is incompatible with Mixin as a whole. For example it will also crash with Et Futurum Requiem (which shades base Mixin 0.7.11).

I recommend [DTools](https://github.com/makamys/DTools) and [LaunchTweaks](https://github.com/makamys/LaunchTweaks) as alternatives that do pretty much the same thing as LoadingProfiler without violently breaking everything.
