### ISSUE TITLE
crashed with iChunUtil

### ISSUE THREAD

**Issue by Kaguya233qwq** [LegacyModdingMC/UniMixins#23]
When I trying put the unimixins with a lib called [iChunUtil](https://github.com/iChun/iChunUtil) ,my game crashed. Please help me to fix it.Thanks a lot.
[minecraft-exported-logs-2024-02-06T12-32-09.log](https://github.com/LegacyModdingMC/UniMixins/files/14174899/minecraft-exported-logs-2024-02-06T12-32-09.log)

**Comment by makamys** [comment]
```Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method func_78484_h in mixins.dsurround.early.json:MixinEntityRenderer from mod dsurround cannot reduce visibiliy of PUBLIC target method```

This is an issue with your Dynamic Surroundings fork (I'm glad it uses a different version number than the original otherwise this would've been very confusing!), not something caused by UniMixins. iChunUtil access transforms a method to be public, but DS tries to `@Overwrite` it to be private, causing a conflict. 

The easiest way to fix it is to change the `@Overwrite` method to be public. Alternatively the mixin config plugin can be changed [like this](https://github.com/Roadhog360/Et-Futurum-Requiem/commit/2a9dea89a92786d29f038cf2c4e1500d0e872638) to be less strict about overwrites.

**Comment by Kaguya233qwq** [comment]
I received it.Thank you very much！



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 6, 2024 13:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LegacyModdingMC/UniMixins] crashed with iChunUtil (Issue #23)




 
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method func_78484_h in mixins.dsurround.early.json:MixinEntityRenderer from mod dsurround cannot reduce visibiliy of PUBLIC target method
 
This is an issue with your Dynamic Surroundings fork (I'm glad it uses a different version number than the original otherwise this would've been very confusing!), not something caused by UniMixins. iChunUtil access transforms a method to be public, but DS tries to @Overwrite it to be private, causing a conflict.
 
The easiest way to fix it is to change the @Overwrite method to be public. Alternatively the mixin config plugin can be changed like this to be less strict about overwrites.

**Comment by mist475** [comment]
I just got around to testing this, the conformVisibility should be added to the early mixins json if that's present, not the regular one which is something people should keep in mind

**Comment by makamys** [comment]
It should be added to the json that corresponds to the offending mixin, which was the early one in your case (given that all your mixins are early), but could also be any other one depending on the mod.

**Comment by Kaguya233qwq** [comment]
Okay,I have communicated with author of the ds mod,the problem has solved.Thank you！

---Original---
From: ***@***.***&gt;
Date: Sat, Feb 10, 2024 14:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LegacyModdingMC/UniMixins] iChunUtil crashes with unofficialDynamic Surroundings fork (Issue #23)




 
It should be added to the json that corresponds to the offending mixin, which was the early one in your case (given that all your mixins are early), but could also be any other one depending on the mod.
