### ISSUE TITLE
Crash (not sure exactly what is causing it)

### ISSUE THREAD

**Issue by gmnovakrc** [LegacyModdingMC/UniMixins#3]
Starting to make a modpack using Forge launcher, 1.7.10 of course.
Saw your UniMixins mod and wanted to see if I could get a bunch of optimizing/bug fixing mods to work together.
Doesn't even get to the forge loading mods screen before crashing.

[crash-2023-02-16_02.24.53-client.txt](https://github.com/LegacyModdingMC/UniMixins/files/10753226/crash-2023-02-16_02.24.53-client.txt)

**Comment by Universal118** [comment]
disable mip map fix in falsetweaks.cfg

**Comment by makamys** [comment]
Hodgepodge and FalseTweaks have some overlapping features that are not compatible with each other, luckily both mods are fully configurable so you can solve this by disabling the incompatible features.
