### ISSUE TITLE
incompatible with LOTR and causing too much errors in log

### ISSUE THREAD

**Issue by jrslwium** [LegacyModdingMC/UniMixins#5]
[crash-2023-02-26_16.54.59-client.txt](https://github.com/LegacyModdingMC/UniMixins/files/10833665/crash-2023-02-26_16.54.59-client.txt)
[fml-client-latest.log](https://github.com/LegacyModdingMC/UniMixins/files/10833669/fml-client-latest.log)

**Comment by makamys** [comment]
The second one is an EndlessIDs issue (it tries to load a mixin class that doesn't exist). I'm going to assume the first one is too.
